services:
  simplesaml:
    image: venatorfox/simplesamlphp:latest
    container_name: simplesaml
    restart: unless-stopped
    environment:
      # Logs visibles dans docker logs
      - DOCKER_REDIRECTLOGS=true
      - CONFIG_BASEURLPATH=https://simplesaml.tpiam.internal/simplesaml/
    volumes:
      # Fichier SP : entity ID + quel IdP utiliser
      - ./authsources.php:/var/simplesamlphp/config/authsources.php:ro
      # Métadonnées de Keycloak (certificat de signature, endpoints SSO)
      - ./saml20-idp-remote.php:/var/simplesamlphp/metadata/saml20-idp-remote.php:ro
      # Certificat SP pour signer les AuthnRequests
      - ./certs:/var/simplesamlphp/cert:ro
    networks:
      - NetApp

networks:
  NetApp:
    external: true
